# Generated by Django 4.1 on 2022-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='costum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='markiting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
